############################
## HUGO MODULES
## Install or uninstall themes and plugins here.
## Docs: https://gohugo.io/hugo-modules/
############################

imports:
  - path: https://sarahduan2023.github.io/JinFan-Duan.io/
  - path: github.io/JinFan-Duan.io/

# Install any Hugo Blox within the `hugo-blox/blox/` folder
mounts:
  - source: JinFan-blox/blox/community
    target: layouts/partials/blox/community/
    includeFiles: '**.html'
  - source: hugo-blox/blox/all-access
    target: layouts/partials/blox/
    includeFiles: '**.html'
  - source: hugo-blox/blox
    target: assets/dist/community/blox/
    includeFiles: '**.css'
  - source: layouts
    target: layouts
  - source: assets
    target: assets
